# Generated by Django 3.2 on 2023-06-16 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='分类名')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='problems.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'problems_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'problems_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('title', models.CharField(max_length=200, verbose_name='题目')),
                ('description', mdeditor.fields.MDTextField(verbose_name='题目描述')),
                ('solution', mdeditor.fields.MDTextField(verbose_name='题解')),
                ('difficulty', models.CharField(choices=[('E', '容易'), ('M', '中等'), ('H', '困难')], default='E', max_length=2, verbose_name='难度')),
                ('url', models.URLField(verbose_name='题目链接')),
                ('website', models.CharField(max_length=50, verbose_name='网站')),
                ('review_time', models.DateTimeField(verbose_name='复习时间')),
                ('successes', models.PositiveSmallIntegerField(verbose_name='成功次数')),
                ('failtures', models.PositiveSmallIntegerField(verbose_name='失败次数')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='problems.Tag', verbose_name='标签集合')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'problems_problems',
                'ordering': ('-order', '-review_time'),
                'get_latest_by': 'id',
            },
        ),
    ]
