# Generated by Django 3.2 on 2023-06-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='failtures',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='失败次数'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复习时间'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='successes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='成功次数'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='题目链接'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='网站'),
        ),
    ]
