# Generated by Django 3.2 on 2023-06-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20230616_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problems',
            options={'get_latest_by': 'id', 'ordering': ('-order', '-review_time'), 'verbose_name': '题库', 'verbose_name_plural': '题库'},
        ),
        migrations.AddField(
            model_name='problems',
            name='emphasis',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='重点'),
        ),
    ]
