# Generated by Django 3.2 on 2023-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20230620_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='title',
            field=models.CharField(max_length=190, unique=True, verbose_name='题目'),
        ),
    ]
