# Generated by Django 3.2 on 2023-07-03 22:33

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='题目描述'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='solution',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='题解'),
        ),
    ]
