# Generated by Django 3.2 on 2023-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20230704_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
